/*
 * Created on Nov 25, 2005
 */
package uk.org.ponder.rsf.expander;

import uk.org.ponder.rsf.components.ELReference;

/** One of the valid types that may appear in the "idstrategy" from the UIReplicator
 * placeholder component. For each bean found in the indexable container 
 * specified for the value binding, the EL for members of the replicated 
 * UIBranchContainer are generated by assembling the composite 
 * EL basepath.ID.stubEL, where basepath is as shown in this class, 
 * idfield is the value retrieved from the bean field specified by idfield below,
 * and stubEL is the EL portion already mentioned in the child component, 
 * an instance of UIBound.
 * @author Antranig Basman (antranig@caret.cam.ac.uk)
 *
 */
public class IDRemapStrategy {
  /** The base bean path (probably that of a BeanLocator) in the request-scope
   * container, at which the field value identified below retrieved from a 
   * replicating bean can be applied to retrieve it. 
   */
  public ELReference basepath;
  /** The name of the property from which the ID of a replicating bean may be 
   * read. This ID will be applied not only to the wildcard portion of the
   * replicated EL binding but also to the localID of the replicated container.
   */
  public String idfield = "id";
}
